In [1]:
import torch
import torch.nn as nn

In [30]:
C = nn.Conv2d(1, 1, 3, 2, 0, bias=False)
nn.init.constant_(C.weight, 1.0/9)
X1 = torch.Tensor(list(range(1, 17))).view([1, 1, 4, 4])
X2 = torch.nn.functional.pad(X1, (0, 1, 0, 1), mode="constant", value=0)
X3 = torch.nn.functional.pad(X1, (1, 0, 1, 0), mode="constant", value=0)
print(X1, C.weight)
print(X2, C.weight)
print(X3, C.weight)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) Parameter containing:
tensor([[[[0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111]]]], requires_grad=True)
tensor([[[[ 1.,  2.,  3.,  4.,  0.],
          [ 5.,  6.,  7.,  8.,  0.],
          [ 9., 10., 11., 12.,  0.],
          [13., 14., 15., 16.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]]) Parameter containing:
tensor([[[[0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111]]]], requires_grad=True)
tensor([[[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  1.,  2.,  3.,  4.],
          [ 0.,  5.,  6.,  7.,  8.],
          [ 0.,  9., 10., 11., 12.],
          [ 0., 13., 14., 15., 16.]]]]) Parameter containing:
tensor([[[[0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111],
          [0.1111, 0.1111, 0.1111]]]], requires_grad=True)


In [31]:
print(C(X2))
print(C(X3))

tensor([[[[6., 5.],
          [8., 6.]]]], grad_fn=<ConvolutionBackward0>)
tensor([[[[ 1.5556,  3.3333],
          [ 6.3333, 11.0000]]]], grad_fn=<ConvolutionBackward0>)


In [32]:
C2 = nn.Conv2d(1, 1, 3, 2, 1, bias=False)
nn.init.constant_(C2.weight, 1.0/9)
print(C2(X1))


tensor([[[[ 1.5556,  3.3333],
          [ 6.3333, 11.0000]]]], grad_fn=<ConvolutionBackward0>)
