In [5]:
import torch


class MyDataset(torch.utils.data.Dataset):

    def __init__(self):
        pass

    def __len__(self):
        return 100

    def __getitem__(self, idx):
        return torch.zeros([1]) + idx * 2

dataset = MyDataset()


In [20]:
def f(batch):
    return torch.cat(batch) * 2
dataloader = torch.utils.data.DataLoader(dataset, batch_size=16, shuffle=False, collate_fn=f)
for i in dataloader:
    print(i)

tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48., 52.,
        56., 60.])
tensor([ 64.,  68.,  72.,  76.,  80.,  84.,  88.,  92.,  96., 100., 104., 108.,
        112., 116., 120., 124.])
tensor([128., 132., 136., 140., 144., 148., 152., 156., 160., 164., 168., 172.,
        176., 180., 184., 188.])
tensor([192., 196., 200., 204., 208., 212., 216., 220., 224., 228., 232., 236.,
        240., 244., 248., 252.])
tensor([256., 260., 264., 268., 272., 276., 280., 284., 288., 292., 296., 300.,
        304., 308., 312., 316.])
tensor([320., 324., 328., 332., 336., 340., 344., 348., 352., 356., 360., 364.,
        368., 372., 376., 380.])
tensor([384., 388., 392., 396.])


In [25]:
from glob import glob

for cur_path in glob('../*.py'):
    print(cur_path)

..\dataset.py
..\latent_dataset.py
..\logger.py
..\model_diffusion.py
..\model_discriminator.py
..\model_VAE.py
..\module.py
..\prestage_train.py
..\stable_diffusion.py
..\util.py
