In [2]:
import torch
from einops import rearrange, reduce, repeat

In [13]:
W = torch.arange(0, 16).long()
print(W)

# Split
W = rearrange(W, '( H W ) -> H W', H = 4)
print(W)

# Transpose
W = rearrange(W, 'H W -> W H')
print(W)

W = rearrange(W, '( H1 H2 ) W -> H1 H2 W', H1 = 2)
print(W.shape, W)

W = rearrange(W, 'H1 H2 W -> W H2 H1', H1 = 2)
print(W.shape, W)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])
torch.Size([2, 2, 4]) tensor([[[ 0,  4,  8, 12],
         [ 1,  5,  9, 13]],

        [[ 2,  6, 10, 14],
         [ 3,  7, 11, 15]]])
torch.Size([4, 2, 2]) tensor([[[ 0,  2],
         [ 1,  3]],

        [[ 4,  6],
         [ 5,  7]],

        [[ 8, 10],
         [ 9, 11]],

        [[12, 14],
         [13, 15]]])


In [44]:
import numpy as np
W = np.arange(0, 16)
print(W)

# Split
W = rearrange(W, '( H W ) -> H W', H = 4)
print(W)

W = reduce(W, 'H W -> H 1', 'max')
print(W)

W = repeat(W, 'H 1 -> H 4') 
print(W)

W = repeat(W, 'H C -> (H C)') 
print(W)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 3  3  3  3]
 [ 7  7  7  7]
 [11 11 11 11]
 [15 15 15 15]]
[ 3  3  3  3  7  7  7  7 11 11 11 11 15 15 15 15]
